# -*- coding: utf-8 -*-
"""Latihan 1 Algoritma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m5_62korfG8S14NRa5990a61Mg9PSFea
"""

angka = int(input("Masukkan angka: "))

if angka > 0:
    print("Angka positif")
elif angka < 0:
    print("Angka negatif")
else:
    print("Angka nol")