# -*- coding: utf-8 -*-
"""latihan 2 algoritma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NRCB5wGsxCylj-Z3G52FhATDer32RnxN
"""

angka = int(input("Masukkan angka: "))

if angka % 2 == 0:
    print("Angka genap")
else:
    print("Angka ganjil")