# -*- coding: utf-8 -*-
"""latihan 3 Algoritma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FUzVQunaOqpcC4tToHrd-owHl5_9Kgii
"""

angka = int(input("Masukkan angka: "))

if angka < 2:
    print("Bukan bilangan prima")
else:
    prima = True

    for i in range(2, angka):
        if angka % i == 0:
            prima = False
            break

    if prima:
        print("Bilangan prima")
    else:
        print("Bukan bilangan prima")